export const APP_ROUTES = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  REGISTRATION_SCREEN: 'REGISTRATION_SCREEN',
  MAIN_SCREEN: 'MAIN_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  BOTTOM_TAB: 'BOTTOM_TAB',
  CARD_SCREEM: 'CARD_SCREEM',
  TEST_SCREEN: 'TEST_SCREEN',
  SAME_CARD_SCREEN: 'SAME_CARD_SCREEN',
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
  ENTER_TEXT_TEST: 'ENTER_TEXT_TEST'
};
